version: "3"
services:
  app:
    image: effectivemobile-app:latest
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
      args:
        SWAGGER_HOST_PORT: "localhost:8085"
    container_name: effectivemobile-app
    ports:
      - "8085:8080"
    environment:
      EM_DB_HOST: db
      EM_DB_PORT: 5432
      EM_DB_USER: admin
      EM_DB_PASSWORD: 1
      EM_DB_NAME: effectivemobile
      EM_HTTP_HOST: localhost
      EM_HTTP_PORT: 8080
      EM_SWAGGER_HOST_PORT: localhost:8085
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:13
    container_name: effectivemobile-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: effectivemobile
    networks:
      - default

volumes:
  dbdata: