# curl -X POST --location "http://localhost:8080/addUser"
#    -H "accept: application/json"
#    -H "Content-Type: application/json"
#    -d "{
#          \"name\": \"Lena\",
#          \"surname\": \"Ushakova\"
#        }"
POST http://localhost:8080/addUser
accept: application/json
Content-Type: application/json

{
  "name": "Lena",
  "surname": "Ushakova"
}


###
# curl -X DELETE --location "http://localhost:8080/deleteUser?id=1"
DELETE http://localhost:8080/deleteUser?id=1


###
# curl -X POST --location "http://localhost:8080/updateUser"
#    -H "accept: application/json"
#    -H "Content-Type: application/json"
#    -d "{
#          \"id\": 1,
#          \"name\": \"Tyrone\",
#          \"surname\": \"Ushakov\"
#        }"
POST http://localhost:8080/updateUser
accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "Tyrone",
  "surname": "Ushakov"
}


###
# curl -X GET --location "http://localhost:8080/getUser?name_like=Len"
GET localhost:8080/getUser?name_like=Len


### wrong pagination options example
# curl -X GET --location "http://localhost:8080/getUser?name_like=Len&page_size=0&page_num=2"
GET localhost:8080/getUser?name_like=Len&page_size=0&page_num=2


### get all users
# curl -X GET --location "http://localhost:8080/getUser"
GET localhost:8080/getUser









