
###
POST localhost:8080/addUser
accept: application/json
Content-Type: application/json

{
  "name": "Lena",
  "surname": "Ushakov"
}

###
DELETE localhost:8080/deleteUser?id=1

###
POST localhost:8080/updateUser
accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "Tyrone",
  "surname": "Ushakov"
}

###
GET localhost:8080/getUser?name_like=Len&page_size=2&page_num=2






